[[build.buildpacks]]
uri =  "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.tar"

[[build.buildpacks]]
uri = "heroku/python"

[[build.buildpacks]]
uri =  "https://github.com/xrisk/heroku-opus.tar"
