[[build.buildpacks]]
url = 'https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest'

[[build.buildpacks]]
uri = "heroku/python"

[[build.buildpacks]]
url = 'https://github.com/xrisk/heroku-opus'
